import "@/styles/reset.css";
import "@/styles/variables.css";
import "@/styles/globals.css";
import { geistMono, geistSans, mainFont } from "@/libs/font";
import {Footer} from "@/components/footer";

export const metadata = {
  title: "Next AI Imaginer",
  description: "Imaginer is a simple image generator that use your prompt. Generated by Berk",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${
            // geistSans.variable
            ""
          }
          ${
            // geistMono.variable
            ""
          } 
          ${mainFont.className} antialiased layout`}
      >
        {children}
        <Footer />
        <div className="overlay" />
      </body>
    </html>
  );
}
